# Generated by Django 3.0.6 on 2020-06-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='img'),
        ),
    ]
