# Generated by Django 3.0.6 on 2020-06-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200601_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name_plural': 'goods'},
        ),
    ]
