version: "3"
services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  web:
    container_name: web
    build: ./shop
    command: /usr/local/bin/uwsgi --ini /src/uwsgi.ini
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: shop-db
    environment:
      POSTGRES_DB: "internet-shop"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
#      - "./db-data:/var/lib/postgresql/data"
      - django-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  django-db-data:
